# Generated by Django 4.2.2 on 2023-07-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0002_author_delete_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=100)),
                ('book_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('payment_method', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('role_title', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('Role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brs.role')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brs.user')),
                ('Workhours', models.IntegerField()),
            ],
            bases=('brs.user',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('books', models.ManyToManyField(to='brs.book')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brs.payment')),
                ('Librarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brs.librarian')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brs.book')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_location', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brs.order')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brs.author'),
        ),
        migrations.AddField(
            model_name='librarian',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brs.offer'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brs.user')),
                ('Payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brs.payment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brs.order')),
            ],
            bases=('brs.user',),
        ),
    ]
