# Generated by Django 4.2.2 on 2023-07-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0003_book_payment_role_user_author_author_id_librarian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.IntegerField(default=0),
        ),
    ]
