# Generated by Django 4.2.2 on 2023-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0004_alter_role_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.IntegerField(default=0),
        ),
    ]
