# Generated by Django 4.2.2 on 2023-07-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0005_alter_payment_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
