# Generated by Django 4.2.2 on 2023-07-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0006_rename_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='role',
        ),
    ]
