# Generated by Django 4.2.2 on 2023-07-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0008_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Librarian',
        ),
    ]
