# Generated by Django 4.2.2 on 2023-07-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0009_remove_author_author_id_remove_order_librarian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='book',
        ),
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
