# Generated by Django 4.2.2 on 2023-07-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0010_remove_cart_order_remove_customer_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('role_title', models.CharField(max_length=15)),
            ],
        ),
    ]
