# Generated by Django 4.2.2 on 2023-07-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0014_alter_role_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
