# Generated by Django 4.2.2 on 2023-07-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0015_alter_role_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_description', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
