# Generated by Django 4.2.2 on 2023-07-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0016_occupation_delete_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='role_description',
            new_name='Occupation_description',
        ),
    ]
