# Generated by Django 4.2.2 on 2023-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0017_rename_role_description_occupation_occupation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
