# Generated by Django 4.2.2 on 2023-07-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0019_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
