# Generated by Django 4.2.2 on 2023-07-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0020_remove_payment_id_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
