# Generated by Django 4.2.2 on 2023-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0022_alter_payment_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_description', models.CharField(max_length=20)),
            ],
        ),
    ]
