# Generated by Django 4.2.2 on 2023-07-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0023_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
