# Generated by Django 4.2.2 on 2023-07-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0025_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
