# Generated by Django 4.2.2 on 2023-07-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0027_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='id',
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
