# Generated by Django 4.2.2 on 2023-07-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brs', '0035_offer_offer_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
